### ISSUE TITLE
AttributeError: 'dict object has no attribute 'resolution'

### ISSUE THREAD

**Issue by mgbowe1** [Foxboron/Archur#2]
Hi,

I saw your project and thought it looked awsome. However, I received this error while running with the following parameters:
 ```
python archur.py -o myfile.png --text "/root of all evil" --resolution 3840x2160 -fg '#DEDEDE' -bg '#3333DE'
```
It works if I use the default resolution of 1920x1080, not setting it in the command line. If you are strapped for time I can further debug and propse a fix.

Thanks,
mgbowe1

**Comment by Foxboron** [comment]
Fixed with  dac0b59! I thought it was an object for some strange reason.
:shipit:
